[package]
name = "skiplist"
version = "0.1.0"
edition = "2024"

[features]
test-utils = []

[dependencies]
rand = "0.9.2"

[dev-dependencies]
proptest = "1.2"
criterion = { version = "0.7.0", features = ["html_reports"] }

[[bench]]
name = "skiplist_benchmarks"
harness = false
